language: php

php:
  - '7.1'

install:
  - composer install

addons:
  code_climate:
    repo_token: 8023799c9911249afedc10382b471e6559183b03eaa4d560fc7bc13317945e30
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - mediainfo

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mediainfo

after_success:
  - vendor/bin/test-reporter
